defmodule Argonaut.UserPreferences do
  @background_images ~w(
  None
  45degreee_fabric.png
  60degree_gray.png
  absurdidad.png
  agsquare.png
  arab_tile.png
  arches.png
  az_subtle.png
  back_pattern.png
  batthern.png
  bedge_grunge.png
  beige_paper.png
  bgnoise_lg.png
  billie_holiday.png
  binding_light.png
  blizzard.png
  blu_stripes.png
  brickwall.png
  bright_squares.png
  brillant.png
  brushed_alu.png
  brushed_alu_dark.png
  candyhole.png
  cardboard.png
  cardboard_1.png
  cardboard_flat.png
  checkered_pattern.png
  chruch.png
  circles.png
  clean_textile.png
  climpek.png
  cloth_alike.png
  concrete_wall_2.png
  concrete_wall_3.png
  connect.png
  cork_1.png
  corrugation.png
  cracks_1.png
  cream_dust.png
  cream_pixels.png
  creampaper.png
  crisp_paper_ruffles.png
  cross_scratches.png
  crosses.png
  cubes.png
  cutcube.png
  daimond_eyes.png
  debut_light.png
  diagonal-noise.png
  diagonal_striped_brick.png
  diagonal_waves.png
  diagonales_decalees.png
  diamond_upholstery.png
  diamonds.png
  dimension.png
  double_lined.png
  dust.png
  ecailles.png
  egg_shell.png
  elastoplast.png
  elegant_grid.png
  embossed_paper.png
  escheresque.png
  exclusive_paper.png
  extra_clean_paper.png
  fabric_1.png
  fabric_of_squares_gray.png
  fabric_plaid.png
  fake_luxury.png
  fancy_deboss.png
  farmer.png
  felt.png
  first_aid_kit.png
  flowertrail.png
  foggy_birds.png
  foil.png
  frenchstucco.png
  furley_bg.png
  geometry.png
  gold_scale.png
  gplaypattern.png
  gradient_squares.png
  graphy.png
  gray_jean.png
  green_dust_scratch.png
  green_gobbler.png
  grey.png
  grey_sandbag.png
  greyfloral.png
  greyzz.png
  grid.png
  grid_noise.png
  gridme.png
  grilled.png
  groovepaper.png
  grunge_wall.png
  handmadepaper.png
  hexellence.png
  hoffman.png
  honey_im_subtle.png
  husk.png
  ice_age.png
  kindajean.png
  knitted-netting.png
  knitting250px.png
  kuji.png
  large_leather.png
  leather_1.png
  lghtmesh.png
  light_alu.png
  light_checkered_tiles.png
  light_grey_floral_motif.png
  light_honeycomb.png
  light_noise_diagonal.png
  light_toast.png
  light_wool.png
  lightpaperfibers.png
  lil_fiber.png
  lined_paper.png
  linedpaper.png
  linen.png
  little_pluses.png
  little_triangles.png
  littleknobs.png
  lyonnette.png
  merely_cubed.png
  mirrored_squares.png
  mochaGrunge.png
  mooning.png
  nasty_fabric.png
  natural_paper.png
  nistri.png
  noise_lines.png
  noise_pattern_with_crosslines.png
  noisy.png
  noisy_grid.png
  norwegian_rose.png
  old_mathematics.png
  old_wall.png
  otis_redding.png
  p1.png
  p2.png
  p4.png
  p5.png
  p6.png
  paper.png
  paper_1.png
  paper_2.png
  paper_3.png
  paper_fibers.png
  paven.png
  perforated_white_leather.png
  pineapplecut.png
  pinstripe.png
  pixel_weave.png
  plaid.png
  polaroid.png
  polonez_car.png
  polyester_lite.png
  project_papper.png
  ps_neutral.png
  psychedelic_pattern.png
  purty_wood.png
  pw_maze_white.png
  pw_pattern.png
  pyramid.png
  quilt.png
  ravenna.png
  redox_01.png
  redox_02.png
  reticular_tissue.png
  retina_wood.png
  retro_intro.png
  ricepaper.png
  ricepaper2.png
  rip_jobs.png
  rockywall.png
  rough_diagonal.png
  roughcloth.png
  satinweave.png
  scribble_light.png
  shattered.png
  shinecaro.png
  shinedotted.png
  shl.png
  silver_scales.png
  skelatal_weave.png
  skin_side_up.png
  small-crackle-bright.png
  small_tiles.png
  smooth_wall.png
  sneaker_mesh_fabric.png
  snow.png
  soft_circle_scales.png
  soft_pad.png
  soft_wallpaper.png
  solid.png
  squairy_light.png
  square_bg.png
  stacked_circles.png
  stitched_wool.png
  strange_bullseyes.png
  straws.png
  striped_lens.png
  struckaxiom.png
  stucco.png
  subtle_dots.png
  subtle_freckles.png
  subtle_grunge.png
  subtle_orange_emboss.png
  subtle_stripes.png
  subtle_surface.png
  subtle_white_feathers.png
  subtle_zebra_3d.png
  subtlenet2.png
  swirl.png
  tapestry_pattern.png
  tex2res1.png
  tex2res2.png
  tex2res3.png
  tex2res5.png
  textured_paper.png
  textured_stripes.png
  texturetastic_gray.png
  ticks.png
  tileable_wood_texture.png
  tiny_grid.png
  triangles_pattern.png
  triangular.png
  vaio_hard_edge.png
  vichy.png
  vintage_speckles.png
  wall4.png
  washi.png
  wavecut.png
  wavegrid.png
  weave.png
  white_bed_sheet.png
  white_brick_wall.png
  white_carbon.png
  white_carbonfiber.png
  white_leather.png
  white_paperboard.png
  white_plaster.png
  white_sand.png
  white_texture.png
  white_tiles.png
  white_wall.png
  white_wall2.png
  white_wall_hash.png
  white_wave.png
  whitediamond.png
  whitey.png
  wide_rectangles.png
  witewall_3.png
  wood_pattern.png
  worn_dots.png
  xv.png
  )

  def background_image_urls do
    @background_images
    |> Enum.map(fn f -> build_url(f) end)
  end

  def background_image_dropdown do
    @background_images
    |> Enum.map(fn u -> {normalize_filename(u), build_url(u)} end)
  end

  defp build_url("None"), do: ""

  defp build_url(u) do
    "/images/subtle_patterns/#{u}"
  end

  defp normalize_filename(f) do
    f
    |> String.replace(".png", "")
    |> String.split("_")
    |> Enum.map(fn s -> String.capitalize(s) end)
    |> Enum.join(" ")
  end
end
